### ISSUE TITLE
Arduino library?

### ISSUE THREAD

**Issue by zainaliyt** [smaho-engineering/esptouch_flutter#12]
I want to know which library are we supposed to use in arduino ide ??

**Comment by vincevargadev** [comment]
This is a Flutter project and AFAIK it's completely irrelevant which library you use in the Arduino IDE as long as in the end, your firmware+hardwares supports ESP Touch.

**Comment by zainaliyt** [comment]
Could you help me with some code from arduino so that i can test it?

Den tors 4 mars 2021 20:06Vince Varga <notifications@github.com> skrev:

**Comment by max-koehler** [comment]
@zainaliyt ESP-Touch is also know as smart config. Best to Google for `ESP WIFI Smart Config`. There are plenty of examples you can find depending on your MCU and used Libraries.

**Comment by hanen1234** [comment]
I want to know how can be installed RTC DS1307 library arduino?

**Comment by max-koehler** [comment]
@hanen1234 as mentioned early this library isn't building upon Arduino. I'd suggest you ask your question at https://forum.arduino.cc/ or search their board to find the answers you are looking for.
