### ISSUE TITLE
Custom EspTouchResult

### ISSUE THREAD

**Issue by rndsamjin** [smaho-engineering/esptouch_flutter#13]
How to make custom EspTouchResult??
EsptouchResult = {"bssid": "10521cb6947c", "ip": "192.168.1.142", "deviceID":"EXAMPLE DEVICE ID", "cancelled": false, "success": true}

**Comment by vincevargadev** [comment]
This is not supported and custom results are not part of ESP Touch.

You can take the IP address and then make HTTP call to your embedded device (for example HTTP GET to `192.168.1.142/someCustomEndpoint`. This also assumes you understand embedded programming and you can set up a custom HTTP endpoint from which you can return any custom information you want.
