### ISSUE TITLE
latest version not working 

### ISSUE THREAD

**Issue by sudhakardharmaraju** [smaho-engineering/esptouch_flutter#15]
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method ssid on channel eng.smaho.com/esptouch_plugin/example)
E/flutter (23722): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (23722): <asynchronous suspension>
E/flutter (23722): #1      ssid (package:join_kit/wifi_info.dart:9:10)
E/flutter (23722): <asynchronous suspension>
E/flutter (23722): #2      _MyAppState.fetchWifiInfo (package:join_kit/main.dart:104:20)
E/flutter (23722): <asynchronous suspension>

**Comment by sudhakardharmaraju** [comment]
======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel eng.smaho.com/esptouch_plugin/results:
MissingPluginException(No implementation found for method listen on channel eng.smaho.com/esptouch_plugin/results)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:545:9)
<asynchronous suspension>

**Comment by sosaucily** [comment]
I also have had trouble getting the ssid using the custom flutter channel when on ios. Not sure if this is even implemented?

But as the developer mentioned, probably better to use a network_info specific library for getting the built in ssid. Those libraries are going to be updated and built just for this purpose. 

I am using https://pub.dev/packages/network_info_plus this one for filling the ssid.

**Comment by myfreax** [comment]
> ======== Exception caught by services library ====================================================== The following MissingPluginException was thrown while activating platform stream on channel eng.smaho.com/esptouch_plugin/results: MissingPluginException(No implementation found for method listen on channel eng.smaho.com/esptouch_plugin/results)
> 
> When the exception was thrown, this was the stack: #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7) #1 EventChannel.receiveBroadcastStream. (package:flutter/src/services/platform_channel.dart:545:9)

Can you tell me how to resolved this?

**Comment by vincevargadev** [comment]
Use the [`network_info_plus`](https://pub.dev/packages/network_info_plus) to get the WiFi SSID (it's the WiFi name).
