### ISSUE TITLE
Not working on ios14

### ISSUE THREAD

**Issue by tamahos** [smaho-engineering/esptouch_flutter#16]
I have been using this with no problem until I'm updating to ios14 and esptouch stop working  and get error

client: sendto fail, but just ignore it
: No route to host

**Comment by cmsong-shina** [comment]
same here on ios 14.6

**Comment by tmdnltclffl** [comment]
same here on ios 14.6

**Comment by max-koehler** [comment]
We'll look into it.

**Comment by tamahos** [comment]
I have fix this problem. request and use this [https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_multicast](url) entitlement.

**Comment by ducnguyenenterprise** [comment]
This is hidden capabilities, you need to request it as account holder [here](https://developer.apple.com/contact/request/networking-multicast).
And config it as [here](https://developer.apple.com/forums/thread/663271)
![Screen Shot 2021-06-21 at 17 24 50](https://user-images.githubusercontent.com/50801656/122798220-87f39580-d2ea-11eb-838e-faeeed28fc8e.png)

**Comment by rndsamjin** [comment]
@tamahos and @ducnguyenenterprise  I already send the request and apple reply like this

> Thank you for your interest in Multicast Networking. Can you please provide more details on which multicast or broadcast protocol (IP address and port) you need to use? What messages are exchanged between devices?

what should be answered?

thank for you advice

**Comment by ducnguyenenterprise** [comment]
Closed this issue as the guide to resolve has been updated in [readme](https://github.com/smaho-engineering/esptouch_flutter/commit/79458f336669f14a9a3397ed6a59409ff17b6d10)
