### ISSUE TITLE
Error: Cannot run with sound null safety

### ISSUE THREAD

**Issue by abobija** [smaho-engineering/esptouch_flutter#17]
I cannot build my project with this library included.
I'm getting this error:

```
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

- package:esptouch_flutter

For solutions, see https://dart.dev/go/unsound-null-safety
```

Can you please make this library to support null safety?

**Comment by max-koehler** [comment]
The support of null safety is on our list but not a top priority at the moment, which is why i can't tell when it will be supported. 
Having said that, we'd be happy to help you, if you want to fix that issue yourself.

**Comment by abobija** [comment]
Nevermind, I have wrote full library in plain Dart, no platform specific.
Thank you anyway for quick answer and willingness to help.

**Comment by MaheshParuchuri** [comment]
> @max-koehler
> Nevermind, I have wrote full library in plain Dart, no platform specific.
> Thank you anyway for quick answer and willingness to help.
Sir can you help me by sharing the code. It helps me more and more for my project

**Comment by abobija** [comment]
@MaheshParuchuri [esp_smartconfig](https://pub.dev/packages/esp_smartconfig)

**Comment by MaheshParuchuri** [comment]
How to use your esp_smartconfig it bit confusion

**Comment by vincevargadev** [comment]
It should be now possible to use the app with sound null safety

https://pub.dev/packages/esptouch_flutter/changelog

**Comment by abobija** [comment]
Thanks @vincevargadev
