### ISSUE TITLE
ESPtouch Issuse.

### ISSUE THREAD

**Issue by MaheshParuchuri** [smaho-engineering/esptouch_flutter#18]
Null Safety and device count is not working.
When two ESP are in on it is connected to two ESP's but for only one ESP the data is Going .
Please Resolve it sir.

**Comment by max-koehler** [comment]
@MaheshParuchuri I saw that you were also involved in issue #17 
As mentioned in that issue, we can't give a timeline when null safety will be supported, but welcome everyone to open PR and contribute to the codebase. 

Regarding your second issue with multiple device, you would need to provide more information. Are you using the example code? Are both devices connected successfully?

**Comment by rndsamjin** [comment]
> Null Safety and device count is not working.
> When two ESP are in on it is connected to two ESP's but for only one ESP the data is Going .
> Please Resolve it sir.

try this,
at this at top of your main.dart or esptouch plugin main.drt
`// @dart=2.11` or `// @dart=2.9`

**Comment by vincevargadev** [comment]
Null safety landed in 1.0.0. Please check if your issue still exist and please clarify your issue if it does. A minimum reproducible example would be great.
