### ISSUE TITLE
[Question] Can i use smartconfig without WiFi BSSID input?

### ISSUE THREAD

**Issue by pdt590** [smaho-engineering/esptouch_flutter#22]
Dear author

Just a question about smartconfig. 
Can i use smartconfig without WiFi BSSID input?

Thank you and have a nice day

**Comment by vincevargadev** [comment]
No, the BSSID and SSID are required. Password can be left empty.

**Comment by em-te** [comment]
Why is BSSID required? Why can't ESP connect based on the wifi name only?

Coming from React Native, one of the plugins for React Native allow to use empty string for BSSID and it can still connect.
https://www.npmjs.com/package/react-native-smartconfig-iot/v/0.2.4
