### ISSUE TITLE
How to send some other info with ip adress

### ISSUE THREAD

**Issue by mralperem** [smaho-engineering/esptouch_flutter#23]
Hello,

When i connected successfully i see the ip adress of the module and the bssid information on my app. 

How can i send some other information to app alongside the ip and bssid when connected successfully?

**Comment by vincevargadev** [comment]
ESP-Touch doesn't support this (or at least doesn't support this out-of-the-box). What you can do is
1. run an HTTP server on your embedded device
2. add an endpoint where the embedded device serves every additional info you need in the app
3. make an HTTP requests from the app (and now you have the IP of the embedded device, and the mobile and the embedded device are probably on the same network, so you can easily do that)

**Comment by vincevargadev** [comment]
Hi @mralperem, Could you solve your issue?
