### ISSUE TITLE
need support V2 embedding. 

### ISSUE THREAD

**Issue by Wingge** [smaho-engineering/esptouch_flutter#29]
The plugin `esptouch_flutter` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by johnwargo** [comment]
#28 addresses this issue, is there a reason someone hasn't looked at the PR?

**Comment by vincevargadev** [comment]
I'll take a look and if everything is OK, I'll merge the PR this weekend.

**Comment by vincevargadev** [comment]
I published a pre-release version on pub.dev https://pub.dev/packages/esptouch_flutter/versions/1.1.0-androidv2

Please give it a try, and let us know if anything is not working as it did before.

If we don't receive any negative feedback, I'll release it as stable in a couple of weeks.

**Comment by Wingge** [comment]
The pre-release version work good.Thank you!
