### ISSUE TITLE
ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method ssid on channel eng.smaho.com/esptouch_plugin/example)

### ISSUE THREAD

**Issue by sukesh0096** [smaho-engineering/esptouch_flutter#32]
can't fetch current wifi ssid and bssid.

getting the below error.

ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method ssid on channel eng.smaho.com/esptouch_plugin/example)

**Comment by vincevargadev** [comment]
Use the [`network_info_plus`](https://pub.dev/packages/network_info_plus) package to get the WiFi SSID and BSSID of the user (and the [`connectivity_plus`](https://pub.dev/packages/connectivity_plus) package if your app needs it). You might also need the [`permission_handler`](https://pub.dev/packages/permission_handler) to ask the user for permission for your app to be able to access the WiFi details.

The example app uses platform specific code (you can find it [here on iOS](https://github.com/smaho-engineering/esptouch_flutter/blob/master/example/ios/Runner/AppDelegate.m) and [here on Android](https://github.com/smaho-engineering/esptouch_flutter/blob/master/example/android/app/src/main/java/com/smaho/eng/esptouchexample/MainActivity.java)) that is part of the example app.

We have an issue (#10) for updating the example app, community contributions are welcome.

For real apps, I recommend you use the plugins that I mentioned above in the first paragraph of this comment.
